import { NextResponse } from "next/server"
import { getUser } from "@/app/actions/auth"
import { createServiceRoleSupabaseClient } from "@/lib/supabase"

export const runtime = "nodejs"
export const maxDuration = 60

// Streaming AI response to avoid timeout
async function streamAIResponse(prompt: string, reportData: any[]): Promise<string> {
  const apiKey = process.env.DEEPSEEK_API_KEY ||
                 process.env.NEXT_PUBLIC_DEEPSEEK_API_KEY ||
                 ''

  if (!apiKey) {
    throw new Error("DeepSeek API key is not configured")
  }

  // Build the prompt with data context
  const dataContext = formatDataForAI(reportData)
  const fullPrompt = `
You are an educational data analyst for the Ministry of Education in Guyana.
Analyze the following school report data and provide insights based on this request: "${prompt}"

Report Data Summary:
${dataContext}

Instructions:
- Start directly with your analysis - do NOT use memorandum format
- Provide professional, actionable insights
- Focus on educational outcomes and trends
- Be concise but thorough
- Format with ## headers and bullet points

Begin your analysis:`

  const response = await fetch("https://api.deepseek.com/chat/completions", {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${apiKey}`
    },
    body: JSON.stringify({
      model: "deepseek-chat",
      messages: [
        {
          role: "system",
          content: "You are an educational data analyst. Provide concise, actionable insights. Do NOT use memorandum format."
        },
        {
          role: "user",
          content: fullPrompt
        }
      ],
      temperature: 0.5,
      max_tokens: 1000, // Reduced for faster response
      stream: false
    })
  })

  if (!response.ok) {
    const errorText = await response.text()
    throw new Error(`AI service error: ${response.status} - ${errorText}`)
  }

  const data = await response.json()

  if (data.choices && data.choices[0] && data.choices[0].message) {
    return data.choices[0].message.content
  }

  throw new Error('No content generated by AI service')
}

// Format data for AI - keep it minimal to reduce processing time
function formatDataForAI(reports: any[]): string {
  if (!reports || reports.length === 0) {
    return "No data available."
  }

  const total = reports.length

  // Calculate quick aggregates
  const stats: string[] = [`Total records: ${total}`]

  // Get unique schools and regions
  const schools = new Set(reports.map(r => r.school_name).filter(Boolean))
  const regions = new Set(reports.map(r => r.region_name).filter(Boolean))

  stats.push(`Schools: ${schools.size}`)
  stats.push(`Regions: ${regions.size}`)

  // Add numeric averages
  const numericFields = [
    { field: 'attendance_rate', label: 'Avg Attendance Rate' },
    { field: 'punctuality_rate', label: 'Avg Punctuality Rate' },
    { field: 'total_enrollment', label: 'Total Enrollment' }
  ]

  for (const { field, label } of numericFields) {
    const values = reports.filter(r => r[field] != null).map(r => Number(r[field]))
    if (values.length > 0) {
      const avg = (values.reduce((a, b) => a + b, 0) / values.length).toFixed(1)
      stats.push(`${label}: ${avg}${field.includes('rate') ? '%' : ''}`)
    }
  }

  // Add sample of 5 records for context
  const sample = reports.slice(0, 5).map((r, i) =>
    `${i + 1}. ${r.school_name || 'Unknown'}: ${r.attendance_rate || r.total_enrollment || 'N/A'}`
  ).join('\n')

  return `${stats.join('\n')}\n\nSample records:\n${sample}`
}

type Body = {
  prompt: string
  reportType: string
  filters?: {
    month?: string
    year?: string
    region?: string
    schoolId?: string
  }
}

export async function POST(req: Request) {
  try {
    const body = (await req.json().catch(() => null)) as Body | null

    if (!body?.prompt || !body?.reportType) {
      return NextResponse.json(
        { insight: null, error: "Missing prompt or reportType." },
        { status: 400 }
      )
    }

    const user = await getUser()

    if (!user) {
      return NextResponse.json(
        { insight: null, error: "User not authenticated." },
        { status: 401 }
      )
    }

    if (user.role !== "Education Official" && user.role !== "Admin" && user.role !== "Regional Officer") {
      return NextResponse.json(
        { insight: null, error: "Only Education Officials, Regional Officers, and Admins can access AI insights." },
        { status: 403 }
      )
    }

    // Fetch relevant report data based on reportType and filters
    const reportData = await fetchReportData(body.reportType, body.filters)

    if (!reportData || !Array.isArray(reportData) || reportData.length === 0) {
      return NextResponse.json(
        { insight: null, error: "No report data found for the selected criteria." },
        { status: 404 }
      )
    }

    // Generate AI insight using streamlined function
    const insight = await streamAIResponse(body.prompt, reportData)

    return NextResponse.json({ insight, error: null })
  } catch (error) {
    console.error("/api/ai-insights error:", error)
    return NextResponse.json(
      {
        insight: null,
        error: error instanceof Error ? error.message : "Failed to generate AI insight.",
      },
      { status: 500 }
    )
  }
}

// Fetch report data based on type and filters
async function fetchReportData(reportType: string, filters?: {
  month?: string
  year?: string
  region?: string
  schoolId?: string
}) {
  const supabase = createServiceRoleSupabaseClient()

  try {
    // Build base query for hmr_report to get report IDs
    let reportQuery = supabase
      .from("hmr_report")
      .select("id, school_id, region_id, month, year, status, sms_schools(name), sms_regions(name))")
      .eq("status", "submitted")

    // Apply filters - month and year are stored as text numbers (e.g., "1", "2025")
    if (filters?.month && filters.month !== "all") {
      reportQuery = reportQuery.eq("month", filters.month)
    }

    if (filters?.year && filters.year !== "all") {
      reportQuery = reportQuery.eq("year", filters.year)
    }

    const { data: reports, error: reportError } = await reportQuery

    console.log("Filters received:", filters)
    console.log("Report query error:", reportError)
    console.log("Reports found:", reports?.length || 0)

    if (reportError) {
      console.error("Error fetching reports:", reportError)
      return []
    }

    if (!reports || reports.length === 0) {
      console.log("No reports found with status 'submitted'")
      return []
    }

    // Filter by region if specified
    let filteredReports = reports
    if (filters?.region) {
      console.log("Filtering by region:", filters.region)
      console.log("Sample report region data:", reports[0]?.sms_regions)
      filteredReports = reports.filter((r: any) =>
        r.sms_regions?.name === filters.region
      )
      console.log("Reports after region filter:", filteredReports.length)
    }

    const reportIds = filteredReports.map((r: any) => r.id)

    if (reportIds.length === 0) {
      console.log("No reports found after filtering")
      return []
    }

    // Fetch data based on report type
    let dataTable = ""
    switch (reportType) {
      case "attendance":
        dataTable = "hmr_attendance"
        break
      case "student-enrollment":
        dataTable = "hmr_student_enrollment"
        break
      case "staffing":
        dataTable = "hmr_staffing"
        break
      case "staff-development":
        dataTable = "hmr_staff_development"
        break
      case "supervision":
        dataTable = "hmr_supervision"
        break
      case "curriculum":
        dataTable = "hmr_curriculum_monitoring"
        break
      case "finance":
        dataTable = "hmr_finance"
        break
      case "income-sources":
        dataTable = "hmr_income_sources"
        break
      case "safety":
        dataTable = "hmr_safety"
        break
      case "staff-meetings":
        dataTable = "hmr_staff_meetings"
        break
      case "physical-facilities":
        dataTable = "hmr_physical_facilities"
        break
      case "resources":
        dataTable = "hmr_resources_needed"
        break
      case "physical-education":
        dataTable = "hmr_physical_education"
        break
      case "all-reports":
        // For all reports, fetch a summary from multiple tables
        return await fetchAllReportsData(reportIds, filteredReports)
      default:
        return []
    }

    const { data, error } = await supabase
      .from(dataTable)
      .select("*")
      .in("report_id", reportIds)
      .limit(100) // Limit records to prevent timeout

    if (error) {
      console.error(`Error fetching ${dataTable}:`, error)
      return []
    }

    // Enrich data with school info
    const enrichedData = data?.map((item: any) => {
      const report = filteredReports.find((r: any) => r.id === item.report_id)
      return {
        ...item,
        school_name: report?.sms_schools?.name || "Unknown School",
        region_name: report?.sms_regions?.name || "Unknown Region",
        report_month: report?.month || "Unknown"
      }
    })

    return enrichedData || []
  } catch (error) {
    console.error("Error in fetchReportData:", error)
    return []
  }
}

async function fetchAllReportsData(reportIds: string[], reports: any[]) {
  const supabase = createServiceRoleSupabaseClient()
  const allData: any[] = []

  const tables = [
    { name: "hmr_attendance", label: "Attendance" },
    { name: "hmr_student_enrollment", label: "Student Enrollment" },
    { name: "hmr_staffing", label: "Staffing" },
    { name: "hmr_finance", label: "Finance" }
  ]

  for (const table of tables) {
    const { data } = await supabase
      .from(table.name)
      .select("*")
      .in("report_id", reportIds)
      .limit(50)

    if (data && data.length > 0) {
      const enriched = data.map((item: any) => {
        const report = reports.find((r: any) => r.id === item.report_id)
        return {
          ...item,
          data_type: table.label,
          school_name: report?.sms_schools?.name || "Unknown",
          region_name: report?.sms_regions?.name || "Unknown"
        }
      })
      allData.push(...enriched)
    }
  }

  return allData
}
