import { getAllAccessTokens } from "@/app/actions/access-tokens"
import { Button } from "@/components/ui/button"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { KeyIcon, Clock, User, CheckCircle, XCircle } from "lucide-react"
import { formatDistanceToNow } from "date-fns"

export default async function AccessTokensPage() {
  const { tokens, error } = await getAllAccessTokens()

  if (error) {
    return (
      <div className="space-y-6">
        <h2 className="text-2xl font-bold">Access Tokens</h2>
        <div className="text-center py-8 text-red-600">
          Error loading access tokens: {error}
        </div>
      </div>
    )
  }

  const activeTokens = tokens.filter(token => !token.is_used && new Date(token.expires_at) > new Date())
  const expiredTokens = tokens.filter(token => !token.is_used && new Date(token.expires_at) <= new Date())
  const usedTokens = tokens.filter(token => token.is_used)

  return (
    <div className="space-y-6">
      <div>
        <h2 className="text-2xl font-bold">Access Tokens</h2>
        <p className="text-muted-foreground">
          Manage access tokens for user impersonation. Tokens are single-use and expire after 24 hours.
        </p>
      </div>

      {/* Statistics */}
      <div className="grid gap-4 md:grid-cols-3">
        <Card>
          <CardHeader className="flex flex-row items-center justify-between pb-2 space-y-0">
            <CardTitle className="text-sm font-medium">Active Tokens</CardTitle>
            <CheckCircle className="h-4 w-4 text-green-600" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-green-600">{activeTokens.length}</div>
            <p className="text-xs text-muted-foreground">Valid and unused</p>
          </CardContent>
        </Card>
        
        <Card>
          <CardHeader className="flex flex-row items-center justify-between pb-2 space-y-0">
            <CardTitle className="text-sm font-medium">Expired Tokens</CardTitle>
            <Clock className="h-4 w-4 text-amber-600" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-amber-600">{expiredTokens.length}</div>
            <p className="text-xs text-muted-foreground">Expired unused tokens</p>
          </CardContent>
        </Card>
        
        <Card>
          <CardHeader className="flex flex-row items-center justify-between pb-2 space-y-0">
            <CardTitle className="text-sm font-medium">Used Tokens</CardTitle>
            <XCircle className="h-4 w-4 text-gray-600" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-gray-600">{usedTokens.length}</div>
            <p className="text-xs text-muted-foreground">Successfully used tokens</p>
          </CardContent>
        </Card>
      </div>

      {/* Tokens Table */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <KeyIcon className="h-5 w-5" />
            All Access Tokens
          </CardTitle>
          <CardDescription>
            Recent access tokens generated by administrators
          </CardDescription>
        </CardHeader>
        <CardContent>
          {tokens.length === 0 ? (
            <div className="text-center py-8 text-muted-foreground">
              No access tokens have been generated yet.
            </div>
          ) : (
            <div className="border rounded-lg overflow-hidden">
              <div className="overflow-x-auto">
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead>Target User</TableHead>
                      <TableHead>Created By</TableHead>
                      <TableHead>Status</TableHead>
                      <TableHead>Created</TableHead>
                      <TableHead>Expires</TableHead>
                      <TableHead>Used</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {tokens.map((token) => {
                      const isExpired = new Date(token.expires_at) <= new Date()
                      const targetUser = token.hmr_users as any
                      const createdByUser = token.created_by_user as any
                      
                      return (
                        <TableRow key={token.id}>
                          <TableCell>
                            <div className="flex items-center gap-2">
                              <User className="h-4 w-4 text-muted-foreground" />
                              <div>
                                <div className="font-medium">{targetUser?.name || 'Unknown'}</div>
                                <div className="text-sm text-muted-foreground">{targetUser?.email}</div>
                              </div>
                            </div>
                          </TableCell>
                          <TableCell>{createdByUser?.name || 'Unknown'}</TableCell>
                          <TableCell>
                            {token.is_used ? (
                              <Badge variant="secondary" className="bg-gray-100 text-gray-700">
                                Used
                              </Badge>
                            ) : isExpired ? (
                              <Badge variant="destructive">
                                Expired
                              </Badge>
                            ) : (
                              <Badge variant="default" className="bg-green-100 text-green-700">
                                Active
                              </Badge>
                            )}
                          </TableCell>
                          <TableCell className="text-sm">
                            {formatDistanceToNow(new Date(token.created_at), { addSuffix: true })}
                          </TableCell>
                          <TableCell className="text-sm">
                            {isExpired ? (
                              <span className="text-red-600">
                                {formatDistanceToNow(new Date(token.expires_at), { addSuffix: true })}
                              </span>
                            ) : (
                              <span className="text-green-600">
                                {formatDistanceToNow(new Date(token.expires_at), { addSuffix: true })}
                              </span>
                            )}
                          </TableCell>
                          <TableCell className="text-sm">
                            {token.used_at ? (
                              formatDistanceToNow(new Date(token.used_at), { addSuffix: true })
                            ) : (
                              <span className="text-muted-foreground">-</span>
                            )}
                          </TableCell>
                        </TableRow>
                      )
                    })}
                  </TableBody>
                </Table>
              </div>
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  )
}