// AI service for generating educational insights using DeepSeek
export class AIService {
  private apiKey: string
  private apiUrl = "https://api.deepseek.com/chat/completions"
  private model = "deepseek-chat"

  constructor() {
    // Check multiple possible environment variable names for maximum compatibility
    const key = process.env.DEEPSEEK_API_KEY || 
                process.env.NEXT_PUBLIC_DEEPSEEK_API_KEY || 
                process.env.NEXT_APP_DEEPSEEK_API_KEY ||
                process.env.NEXT_PUBLIC_GEMINI_API_KEY || // Fallback in case user reused the old name
                '';
    
    this.apiKey = key.trim();
    
    if (!this.apiKey) {
      const allKeys = Object.keys(process.env);
      const aiRelatedKeys = allKeys.filter(k => 
        k.includes('DEEPSEEK') || 
        k.includes('GEMINI') || 
        k.includes('AI') || 
        k.includes('API_KEY')
      );
      
      console.error('AIService: DeepSeek API key is missing.', {
        checkedKeys: ['DEEPSEEK_API_KEY', 'NEXT_PUBLIC_DEEPSEEK_API_KEY', 'NEXT_APP_DEEPSEEK_API_KEY', 'NEXT_PUBLIC_GEMINI_API_KEY'],
        foundAiRelatedKeys: aiRelatedKeys,
        nodeEnv: process.env.NODE_ENV,
        isServer: typeof window === 'undefined'
      });
      
      throw new Error(`DeepSeek API key is required. Please set DEEPSEEK_API_KEY in your deployment environment variables. (Available AI-related keys: ${aiRelatedKeys.length > 0 ? aiRelatedKeys.join(', ') : 'none found'})`);
    }
  }

  async generateInsight(prompt: string, reportData: any[]): Promise<string> {
    const maxRetries = Number.parseInt(process.env.AI_MAX_RETRIES || "1", 10)
    let attempt = 0
    
    while (attempt < maxRetries) {
      try {
        // Netlify/Vercel serverless functions can time out quickly; default to a fail-fast timeout.
        const timeoutMs = Number.parseInt(process.env.AI_REQUEST_TIMEOUT_MS || "6000", 10)
        const controller = new AbortController()
        const timeoutId = setTimeout(() => controller.abort(), Number.isFinite(timeoutMs) ? timeoutMs : 6000)

        const response = await fetch(
          this.apiUrl,
          {
            method: 'POST',
            headers: {
              'Content-Type': 'application/json',
              'Authorization': `Bearer ${this.apiKey}`
            },
            signal: controller.signal,
            body: JSON.stringify({
              model: this.model,
              messages: [
                {
                  role: "system",
                  content: "You are an educational data analyst for the Ministry of Education in Guyana. Provide professional, actionable insights based on school report data. IMPORTANT: Do NOT use memorandum format. Do NOT include TO, FROM, DATE, or SUBJECT fields. Start directly with the analysis content."
                },
                {
                  role: "user",
                  content: this.buildPrompt(prompt, reportData)
                }
              ],
              temperature: 0.5,
              max_tokens: 2000,
            })
          }
        )
        clearTimeout(timeoutId)

        if (response.ok) {
          const data = await response.json()
          
          if (data.choices && data.choices[0] && data.choices[0].message) {
            return data.choices[0].message.content
          }
          
          throw new Error('No content generated by AI service')
        }

        // Handle rate limiting (429) and server errors (5xx) with retry
        if (response.status === 429 || response.status >= 500) {
          attempt++
          if (attempt < maxRetries) {
            const backoffDelay = Math.pow(2, attempt) * 1000 + Math.random() * 1000 
            await this.delay(backoffDelay)
            continue
          }
        }

        // Handle other client errors (4xx) - don't retry
        if (response.status >= 400 && response.status < 500) {
          const errorText = await response.text().catch(() => 'Unknown error')
          throw new Error(`AI service client error (${response.status}): ${response.statusText}. ${errorText}`)
        }

        // Handle other errors
        throw new Error(`AI service error: ${response.status} ${response.statusText}`)

      } catch (error) {
        attempt++

        if (error instanceof DOMException && error.name === "AbortError") {
          throw new Error("AI request timed out. Please try again.")
        }
        
        if ((error instanceof TypeError && error.message.includes('fetch')) && attempt < maxRetries) {
          const backoffDelay = Math.pow(2, attempt) * 1000 + Math.random() * 1000
          await this.delay(backoffDelay)
          continue
        }
        
        if (attempt >= maxRetries) {
          console.error('Error calling AI service after all retries:', error)
          
          if (error instanceof Error) {
            if (error.message.includes('429')) {
              throw new Error('The AI service is currently experiencing high demand. Please try again in a few minutes.')
            } else if (error.message.includes('fetch')) {
              throw new Error('Unable to connect to AI service. Please check your internet connection and try again.')
            } else if (error.message.includes('API key')) {
              throw new Error('AI service configuration error. Please contact system administrator.')
            }
          }
          
          throw new Error('AI service is temporarily unavailable. Please try again later.')
        }
        
        throw error
      }
    }
    
    throw new Error('AI service is temporarily unavailable. Please try again later.')
  }

  private delay(ms: number): Promise<void> {
    return new Promise(resolve => setTimeout(resolve, ms))
  }

  private buildPrompt(userPrompt: string, reportData: any[]): string {
    // Many call sites provide a complete, self-contained prompt (including context and formatting rules).
    // In those cases, avoid bloating the request with redundant wrappers and report dumps.
    if (!reportData || !Array.isArray(reportData) || reportData.length === 0) {
      return userPrompt
    }

    const dataContext = this.formatReportData(reportData)

    return `
You are an educational data analyst for the Ministry of Education in Guyana.
Analyze the following school report data and provide insights based on this request: "${userPrompt}"

Report Data:
${dataContext}

Instructions:
- Start directly with your analysis - do NOT use memorandum format
- Do NOT include TO, FROM, DATE, or SUBJECT fields
- Provide professional, actionable insights
- Focus on educational outcomes and trends
- Suggest concrete recommendations where appropriate
- Use clear, accessible language for educational officials
- Highlight key patterns, challenges, and opportunities
- Format your response with clear sections using ## headers and bullet points
- Always include a final section with actionable recommendations

Begin your analysis:
`
  }

  private formatReportData(reports: any[]): string {
    if (!reports || !Array.isArray(reports) || reports.length === 0) {
      return "No report data available."
    }

    return reports.map((report, index) => {
      let reportText = `
Report ${index + 1}:
- School: ${report.school_name || 'Unknown'}
- Region: ${report.region || report.region_name || 'Unknown'}
- Period: ${report.month}/${report.year}
- Status: ${report.status || 'Unknown'}
`

      // Add section-specific data based on what's available in the report
      if (report.data_type === 'staffing' || report.total_staff_entitlement !== undefined) {
        reportText += `
STAFFING DATA:
- Total Staff Entitlement: ${report.total_staff_entitlement || 'Not specified'}
- Current Teachers: ${report.total_current_teachers || 'Not specified'}
- Under-staffed by: ${report.under_staffed_by || 0} teachers
- Over-staffed by: ${report.over_staffed_by || 0} teachers
- Secondment Certificate: ${report.secondment_attendance_cert ? 'Yes' : 'No'}
`
      }

      // Add attendance data formatting (hmr_attendance table)
      // Fields: type ('student'|'teacher'), attendance_rate, punctuality_rate
      if (report.attendance_rate !== undefined || report.punctuality_rate !== undefined || report.type !== undefined) {
        reportText += `
ATTENDANCE DATA:
- Type: ${report.type || 'Not specified'}
- Attendance Rate: ${report.attendance_rate !== undefined ? `${report.attendance_rate}%` : 'Not specified'}
- Punctuality Rate: ${report.punctuality_rate !== undefined ? `${report.punctuality_rate}%` : 'Not specified'}
`
      }

      // Add teacher status updates formatting (hmr_teacher_status_updates table)
      // Fields: category, teacher_name, teacher_status, reason, offence, days_absent, action_taken
      if (report.data_type === 'teacher_updates' || (report.category !== undefined && report.teacher_name !== undefined)) {
        reportText += `
TEACHER STATUS UPDATE:
- Category: ${report.category || 'Not specified'}
- Teacher Name: ${report.teacher_name || 'Not specified'}
- Teacher Status: ${report.teacher_status || 'Not specified'}
- Reason: ${report.reason || 'Not specified'}
- Offence: ${report.offence || 'Not specified'}
- Days Absent: ${report.days_absent || 'Not specified'}
- Action Taken: ${report.action_taken || 'Not specified'}
`
      }

      // Add student enrollment data formatting (hmr_student_enrollment table)
      // Fields: total_enrollment, transferred_in, transferred_out
      if (report.total_enrollment !== undefined || report.transferred_in !== undefined || report.transferred_out !== undefined) {
        reportText += `
STUDENT ENROLLMENT DATA:
- Total Enrollment: ${report.total_enrollment || 'Not specified'}
- Transferred In: ${report.transferred_in || 0}
- Transferred Out: ${report.transferred_out || 0}
`
      }

      // Add finance data formatting (hmr_finance table)
      // Fields: opening_balance, total_income, total_expenditure, closing_balance
      if (report.opening_balance !== undefined || report.closing_balance !== undefined) {
        reportText += `
FINANCE DATA:
- Opening Balance: ${report.opening_balance || 'Not specified'}
- Total Income: ${report.total_income || 'Not specified'}
- Total Expenditure: ${report.total_expenditure || 'Not specified'}
- Closing Balance: ${report.closing_balance || 'Not specified'}
`
      }

      // Add physical education data formatting (hmr_physical_education table)
      // Fields: activities_performed, challenges
      if (report.activities_performed !== undefined || (report.challenges !== undefined && report.activities_performed !== undefined)) {
        reportText += `
PHYSICAL EDUCATION DATA:
- Activities Performed: ${report.activities_performed || 'Not specified'}
- Challenges: ${report.challenges || 'Not specified'}
`
      }

      // Add income sources data formatting (hmr_income table)
      // Fields: source, amount
      if (report.source !== undefined || report.amount !== undefined) {
        reportText += `
INCOME SOURCE DATA:
- Source: ${report.source || 'Not specified'}
- Amount: ${report.amount || 'Not specified'}
`
      }

      // Add safety/accident data formatting (hmr_accident_safety table)
      // Fields: evacuation_drill, persons_involved, time_taken, observations, 
      //         first_aid_kit, fire_extinguisher, total_accidents, students_involved, 
      //         teachers_involved, actions_taken
      if (report.evacuation_drill !== undefined || report.total_accidents !== undefined || report.first_aid_kit !== undefined) {
        reportText += `
SAFETY/ACCIDENT DATA:
- Evacuation Drill Conducted: ${report.evacuation_drill || 'Not specified'}
- Persons Involved in Drill: ${report.persons_involved || 'Not specified'}
- Time Taken (minutes): ${report.time_taken || 'Not specified'}
- Drill Observations: ${report.observations || 'Not specified'}
- First Aid Kit Available: ${report.first_aid_kit || 'Not specified'}
- Fire Extinguisher Available: ${report.fire_extinguisher || 'Not specified'}
- Total Accidents: ${report.total_accidents || 0}
- Students Involved in Accidents: ${report.students_involved || 0}
- Teachers Involved in Accidents: ${report.teachers_involved || 0}
- Actions Taken: ${report.actions_taken || 'Not specified'}
`
      }

      // Add staff meetings data formatting (hmr_staff_meetings table)
      // Fields: meeting_held, key_issues, decisions_implemented
      if (report.meeting_held !== undefined || report.key_issues !== undefined || report.decisions_implemented !== undefined) {
        reportText += `
STAFF MEETING DATA:
- Meeting Held: ${report.meeting_held || 'Not specified'}
- Key Issues Discussed: ${report.key_issues || 'Not specified'}
- Decisions Implemented (%): ${report.decisions_implemented !== undefined ? `${report.decisions_implemented}%` : 'Not specified'}
`
      }

      // Add physical facilities data formatting (hmr_facilities table)
      // Fields: type ('Teachers'|'Students'), functional_percentage, working_sinks, 
      //         working_taps, overcrowded_classrooms
      if (report.functional_percentage !== undefined || report.working_sinks !== undefined || report.working_taps !== undefined) {
        reportText += `
FACILITIES DATA:
- Facility Type: ${report.type || 'Not specified'}
- Functional Washrooms/Toilets (%): ${report.functional_percentage !== undefined ? `${report.functional_percentage}%` : 'Not specified'}
- Working Sinks (%): ${report.working_sinks !== undefined ? `${report.working_sinks}%` : 'Not specified'}
- Working Taps (%): ${report.working_taps !== undefined ? `${report.working_taps}%` : 'Not specified'}
- Overcrowded Classrooms (%): ${report.overcrowded_classrooms !== undefined ? `${report.overcrowded_classrooms}%` : 'Not specified'}
`
      }

      // Add resources needed data formatting (hmr_resources_needed table)
      // Fields: curriculum_resources, janitorial_supplies, other_issues
      if (report.curriculum_resources !== undefined || report.janitorial_supplies !== undefined || report.other_issues !== undefined) {
        reportText += `
RESOURCES NEEDED DATA:
- Curriculum Resources Needed: ${report.curriculum_resources || 'Not specified'}
- Janitorial Supplies Needed: ${report.janitorial_supplies || 'Not specified'}
- Other Issues/Needs: ${report.other_issues || 'Not specified'}
`
      }

      // Add staff development data formatting (hmr_staff_development table)
      // Fields: session_held, attendance_percentage, topic, outcomes, reason
      if (report.session_held !== undefined || report.topic !== undefined || report.attendance_percentage !== undefined) {
        reportText += `
STAFF DEVELOPMENT DATA:
- PD Session Held: ${report.session_held || 'Not specified'}
- Attendance (%): ${report.attendance_percentage !== undefined ? `${report.attendance_percentage}%` : 'Not specified'}
- Topic: ${report.topic || 'Not specified'}
- Outcomes: ${report.outcomes || 'Not specified'}
- Reason (if not held): ${report.reason || 'Not specified'}
`
      }

      // Add supervision data formatting (hmr_supervision table)
      // Fields: supervisor_type, lessons_observed, positive_findings, negative_findings, follow_up
      if (report.supervisor_type !== undefined || report.lessons_observed !== undefined || report.positive_findings !== undefined) {
        reportText += `
SUPERVISION DATA:
- Supervisor Type: ${report.supervisor_type || 'Not specified'}
- Lessons Observed: ${report.lessons_observed || 'Not specified'}
- Positive Findings: ${report.positive_findings || 'Not specified'}
- Negative Findings: ${report.negative_findings || 'Not specified'}
- Follow-up Actions: ${report.follow_up || 'Not specified'}
`
      }

      // Add curriculum data formatting (hmr_curriculum table)
      // Fields: teachers_without_plans, actions_taken
      if (report.teachers_without_plans !== undefined || (report.actions_taken !== undefined && report.teachers_without_plans !== undefined)) {
        reportText += `
CURRICULUM DATA:
- Teachers Without Lesson Plans: ${report.teachers_without_plans || 0}
- Actions Taken: ${report.actions_taken || 'Not specified'}
`
      }

      return reportText
    }).join('\n')
  }

  // Predefined prompt suggestions for different report sections
  static getPromptSuggestions() {
    return {
      'student-enrollment': [
        'Analyze student enrollment trends across schools and identify patterns',
        'Compare transfer rates between schools and regions',
        'Identify schools with high dropout rates and suggest intervention strategies',
        'Assess enrollment capacity and growth trends for resource planning',
        'Analyze seasonal enrollment patterns and their impact on school operations'
      ],
      'attendance': [
        'Analyze attendance patterns across schools and identify concerning trends',
        'Compare average daily attendance rates between regions and school types',
        'Identify schools with excellent attendance rates and their best practices',
        'Assess the relationship between school days opened and student attendance',
        'Recommend strategies to improve attendance in underperforming schools'
      ],
      'staffing': [
        'Analyze teacher-to-student ratios and staffing adequacy across schools',
        'Identify patterns in teacher absenteeism and suggest solutions',
        'Compare staffing levels between different regions and school types',
        'Assess the impact of staff shortages on educational delivery',
        'Analyze reasons for staff absence and recommend policy interventions'
      ],
      'staff-development': [
        'Evaluate the effectiveness of professional development programs',
        'Identify gaps in teacher training and skill development initiatives',
        'Compare staff development activities across different schools',
        'Assess the impact of training programs on educational outcomes',
        'Recommend priority areas for staff development investment'
      ],
      'supervision': [
        'Analyze supervision practices and their impact on teaching quality',
        'Compare classroom observation frequencies across schools',
        'Identify effective supervision strategies and feedback mechanisms',
        'Assess the quality of principal supervision activities',
        'Recommend improvements to supervision and mentoring programs'
      ],
      'curriculum': [
        'Analyze curriculum implementation progress across schools',
        'Identify gaps in subject-specific teaching and learning',
        'Compare assessment and evaluation practices between schools',
        'Assess alignment between curriculum objectives and actual delivery',
        'Recommend strategies to improve curriculum monitoring and support'
      ],
      'finance': [
        'Analyze school budget management and expenditure patterns',
        'Identify schools facing significant funding challenges',
        'Compare financial management practices across schools',
        'Assess the impact of budget constraints on educational delivery',
        'Recommend strategies for improved financial planning and resource allocation'
      ],
      'income-sources': [
        'Analyze the diversity of income sources across schools',
        'Identify schools with limited income streams and suggest alternatives',
        'Compare government funding vs other income sources',
        'Assess the sustainability of current income patterns',
        'Recommend strategies to increase school funding diversity'
      ],
      'safety': [
        'Analyze accident and safety incident patterns across schools',
        'Identify schools with recurring safety concerns',
        'Compare safety records between different school types',
        'Assess the effectiveness of current safety protocols',
        'Recommend safety improvements and preventive measures'
      ],
      'staff-meetings': [
        'Analyze the frequency and effectiveness of staff meetings',
        'Identify patterns in staff meeting attendance and participation',
        'Compare meeting practices across schools in the region',
        'Assess the quality of meeting documentation and follow-ups',
        'Recommend best practices for productive staff meetings'
      ],
      'physical-facilities': [
        'Analyze the condition of physical facilities across schools',
        'Identify schools with critical infrastructure needs',
        'Compare facility standards between urban and rural schools',
        'Assess maintenance and repair priorities',
        'Recommend capital investment priorities for facilities'
      ],
      'resources': [
        'Analyze resource needs and shortages across schools',
        'Identify the most commonly needed resources in the region',
        'Compare resource allocation between schools',
        'Assess the urgency of different resource requests',
        'Recommend resource procurement and distribution strategies'
      ],
      'physical-education': [
        'Analyze physical education activities across schools and identify the most effective programs',
        'Summarize the main challenges preventing effective physical education delivery',
        'Compare student participation rates in physical education across different regions',
        'Identify schools with innovative physical education approaches and best practices',
        'Assess equipment and facility needs based on reported challenges'
      ],
      'general-overview': [
        'Provide an overall assessment of school performance and reporting trends',
        'Identify schools that need immediate support or intervention',
        'Analyze regional differences in educational outcomes and challenges',
        'Summarize common themes across all submitted reports',
        'Highlight schools demonstrating exceptional performance or innovation'
      ],
      'challenges-analysis': [
        'Categorize and prioritize the most common challenges across all schools',
        'Identify regional patterns in reported challenges and suggest targeted solutions',
        'Analyze resource-related challenges and recommend allocation priorities',
        'Compare urban vs rural school challenges and suggest differentiated support',
        'Identify systemic issues that require policy-level interventions'
      ],
      'trends-forecasting': [
        'Identify emerging trends in education delivery and student outcomes',
        'Predict potential challenges based on current reporting patterns',
        'Analyze seasonal or temporal patterns in educational activities and challenges',
        'Forecast resource needs based on reported trends and growth patterns',
        'Identify opportunities for system-wide improvements and innovations'
      ]
    }
  }

  // Get suggested prompts for a specific category
  static getSuggestedPrompts(category: keyof ReturnType<typeof AIService.getPromptSuggestions>): string[] {
    const suggestions = this.getPromptSuggestions()
    return suggestions[category] || []
  }
}
