// Gemini AI service for generating educational insights
export class GeminiService {
  private apiKey: string
  private apiUrl = "https://generativelanguage.googleapis.com/v1beta/models"
  private model = "gemini-2.0-flash"

  constructor() {
    this.apiKey = process.env.NEXT_PUBLIC_GEMINI_API_KEY || ''
    if (!this.apiKey) {
      throw new Error('Gemini API key is required')
    }
  }

  async generateInsight(prompt: string, reportData: any[]): Promise<string> {
    try {
      const response = await fetch(
        `${this.apiUrl}/${this.model}:generateContent?key=${this.apiKey}`,
        {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({
            contents: [{
              parts: [{
                text: this.buildPrompt(prompt, reportData)
              }]
            }],
            generationConfig: {
              temperature: 0.7,
              topK: 40,
              topP: 0.95,
              maxOutputTokens: 2048,
            }
          })
        }
      )

      if (!response.ok) {
        throw new Error(`Gemini API error: ${response.status} ${response.statusText}`)
      }

      const data = await response.json()
      
      if (data.candidates && data.candidates[0] && data.candidates[0].content) {
        return data.candidates[0].content.parts[0].text
      }
      
      throw new Error('No content generated by Gemini API')
    } catch (error) {
      console.error('Error calling Gemini API:', error)
      throw new Error('Failed to generate AI insight')
    }
  }

  private buildPrompt(userPrompt: string, reportData: any[]): string {
    const dataContext = this.formatReportData(reportData)
    
    return `
You are an educational data analyst for the Ministry of Education in Guyana. 
Analyze the following school report data and provide insights based on this request: "${userPrompt}"

Report Data:
${dataContext}

Instructions:
- Provide professional, actionable insights
- Focus on educational outcomes and trends
- Suggest concrete recommendations where appropriate
- Use clear, accessible language for educational officials
- Highlight key patterns, challenges, and opportunities
- Format your response with clear sections and bullet points where helpful

Analysis:
`
  }

  private formatReportData(reports: any[]): string {
    if (!reports || !Array.isArray(reports) || reports.length === 0) {
      console.log("Invalid reports data:", typeof reports, Array.isArray(reports))
      return "No report data available."
    }

    return reports.map((report, index) => {
      let reportText = `
Report ${index + 1}:
- School: ${report.school_name || 'Unknown'}
- Region: ${report.region || report.region_name || 'Unknown'}
- Period: ${report.month}/${report.year}
- Status: ${report.status || 'Unknown'}
`

      // Add section-specific data based on what's available in the report
      if (report.data_type === 'staffing' || report.total_staff_entitlement !== undefined) {
        reportText += `
STAFFING DATA:
- Total Staff Entitlement: ${report.total_staff_entitlement || 'Not specified'}
- Current Teachers: ${report.total_current_teachers || 'Not specified'}
- Under-staffed by: ${report.under_staffed_by || 0} teachers
- Over-staffed by: ${report.over_staffed_by || 0} teachers
- Secondment Certificate: ${report.secondment_attendance_cert ? 'Yes' : 'No'}
`
      }

      if (report.data_type === 'teacher_updates' || report.category !== undefined) {
        reportText += `
TEACHER STATUS:
- Category: ${report.category || 'Not specified'}
- Teacher Name: ${report.teacher_name || 'Not specified'}
- Status: ${report.teacher_status || 'Not specified'}
- Reason: ${report.reason || 'Not specified'}
- Days Absent: ${report.days_absent || 'Not specified'}
`
      }

      // Generic fields for other types of reports
      if (report.total_students_enrolled !== undefined) {
        reportText += `
ENROLLMENT DATA:
- Total Students: ${report.total_students_enrolled || 'Not specified'}
- Transferred In: ${report.students_transferred_in || 0}
- Transferred Out: ${report.students_transferred_out || 0}
`
      }

      if (report.opening_balance !== undefined) {
        reportText += `
FINANCE DATA:
- Opening Balance: ${report.opening_balance || 'Not specified'}
- Total Income: ${report.total_income || 'Not specified'}
- Total Expenditure: ${report.total_expenditure || 'Not specified'}
- Closing Balance: ${report.closing_balance || 'Not specified'}
`
      }

      return reportText
    }).join('\n')
  }

  // Predefined prompt suggestions for different report sections
  static getPromptSuggestions() {
    return {
      'student-enrollment': [
        'Analyze student enrollment trends across schools and identify patterns',
        'Compare transfer rates between schools and regions',
        'Identify schools with high dropout rates and suggest intervention strategies',
        'Assess enrollment capacity and growth trends for resource planning',
        'Analyze seasonal enrollment patterns and their impact on school operations'
      ],
      'attendance': [
        'Analyze attendance patterns across schools and identify concerning trends',
        'Compare average daily attendance rates between regions and school types',
        'Identify schools with excellent attendance rates and their best practices',
        'Assess the relationship between school days opened and student attendance',
        'Recommend strategies to improve attendance in underperforming schools'
      ],
      'staffing': [
        'Analyze teacher-to-student ratios and staffing adequacy across schools',
        'Identify patterns in teacher absenteeism and suggest solutions',
        'Compare staffing levels between different regions and school types',
        'Assess the impact of staff shortages on educational delivery',
        'Analyze reasons for staff absence and recommend policy interventions'
      ],
      'staff-development': [
        'Evaluate the effectiveness of professional development programs',
        'Identify gaps in teacher training and skill development initiatives',
        'Compare staff development activities across different schools',
        'Assess the impact of training programs on educational outcomes',
        'Recommend priority areas for staff development investment'
      ],
      'supervision': [
        'Analyze supervision practices and their impact on teaching quality',
        'Compare classroom observation frequencies across schools',
        'Identify effective supervision strategies and feedback mechanisms',
        'Assess the quality of principal supervision activities',
        'Recommend improvements to supervision and mentoring programs'
      ],
      'curriculum': [
        'Analyze curriculum implementation progress across schools',
        'Identify gaps in subject-specific teaching and learning',
        'Compare assessment and evaluation practices between schools',
        'Assess alignment between curriculum objectives and actual delivery',
        'Recommend strategies to improve curriculum monitoring and support'
      ],
      'finance': [
        'Analyze school budget management and expenditure patterns',
        'Identify schools facing significant funding challenges',
        'Compare financial management practices across schools',
        'Assess the impact of budget constraints on educational delivery',
        'Recommend strategies for improved financial planning and resource allocation'
      ],
      'physical-education': [
        'Analyze physical education activities across schools and identify the most effective programs',
        'Summarize the main challenges preventing effective physical education delivery',
        'Compare student participation rates in physical education across different regions',
        'Identify schools with innovative physical education approaches and best practices',
        'Assess equipment and facility needs based on reported challenges'
      ],
      'general-overview': [
        'Provide an overall assessment of school performance and reporting trends',
        'Identify schools that need immediate support or intervention',
        'Analyze regional differences in educational outcomes and challenges',
        'Summarize common themes across all submitted reports',
        'Highlight schools demonstrating exceptional performance or innovation'
      ],
      'challenges-analysis': [
        'Categorize and prioritize the most common challenges across all schools',
        'Identify regional patterns in reported challenges and suggest targeted solutions',
        'Analyze resource-related challenges and recommend allocation priorities',
        'Compare urban vs rural school challenges and suggest differentiated support',
        'Identify systemic issues that require policy-level interventions'
      ],
      'trends-forecasting': [
        'Identify emerging trends in education delivery and student outcomes',
        'Predict potential challenges based on current reporting patterns',
        'Analyze seasonal or temporal patterns in educational activities and challenges',
        'Forecast resource needs based on reported trends and growth patterns',
        'Identify opportunities for system-wide improvements and innovations'
      ]
    }
  }

  // Get suggested prompts for a specific category
  static getSuggestedPrompts(category: keyof ReturnType<typeof GeminiService.getPromptSuggestions>): string[] {
    const suggestions = this.getPromptSuggestions()
    return suggestions[category] || []
  }
}
