-- Migration: Create report_recommendations table
-- Description: Stores AI-generated improvement recommendations for assessment reports
-- Recommendations are generated based on weak scoring categories

-- Create enum type for priority levels
DO $$ BEGIN
    CREATE TYPE recommendation_priority AS ENUM ('high', 'medium', 'low');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- Create the school_assessment_recommendations table
CREATE TABLE IF NOT EXISTS school_assessment_recommendations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    
    -- Foreign key to the report
    report_id UUID NOT NULL REFERENCES school_assessment_reports(id) ON DELETE CASCADE,
    
    -- Category this recommendation relates to
    category VARCHAR(50) NOT NULL CHECK (category IN (
        'academic',
        'attendance', 
        'infrastructure',
        'teaching_quality',
        'management',
        'student_welfare',
        'community',
        'general'
    )),
    
    -- Priority level based on score percentage
    -- High: < 40% of max, Medium: 40-60%, Low: > 60% with room for improvement
    priority VARCHAR(10) NOT NULL CHECK (priority IN ('high', 'medium', 'low')),
    
    -- The recommendation text generated by AI
    recommendation_text TEXT NOT NULL,
    
    -- Specific areas to focus on (array of focus points)
    focus_areas TEXT[] DEFAULT '{}',
    
    -- When the recommendation was generated
    generated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    
    -- Audit fields
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Create indexes for efficient queries
CREATE INDEX IF NOT EXISTS idx_recommendations_report ON school_assessment_recommendations(report_id);
CREATE INDEX IF NOT EXISTS idx_recommendations_category ON school_assessment_recommendations(category);
CREATE INDEX IF NOT EXISTS idx_recommendations_priority ON school_assessment_recommendations(priority);

-- Enable Row Level Security
ALTER TABLE school_assessment_recommendations ENABLE ROW LEVEL SECURITY;

-- RLS Policies inherit from parent report access
-- Head Teachers can view recommendations for their school's reports
CREATE POLICY "Head Teachers can view own school recommendations" ON school_assessment_recommendations
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM school_assessment_reports r
            JOIN sms_schools s ON s.id = r.school_id
            JOIN hmr_users u ON u.school_id = s.id
            JOIN hmr_user_roles role ON u.role = role.id
            WHERE r.id = school_assessment_recommendations.report_id
            AND u.id = auth.uid()
            AND role.name = 'Head Teacher'
        )
    );

-- Regional Officers can view recommendations for their region's reports
CREATE POLICY "Regional Officers can view regional recommendations" ON school_assessment_recommendations
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM school_assessment_reports r
            JOIN sms_schools s ON s.id = r.school_id
            JOIN sms_regions reg ON reg.id = s.region_id
            JOIN hmr_users u ON u.region = reg.id
            JOIN hmr_user_roles role ON u.role = role.id
            WHERE r.id = school_assessment_recommendations.report_id
            AND u.id = auth.uid()
            AND role.name = 'Regional Officer'
        )
    );

-- Education Officials can view all recommendations
CREATE POLICY "Education Officials can view all recommendations" ON school_assessment_recommendations
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM hmr_users u
            JOIN hmr_user_roles r ON u.role = r.id
            WHERE u.id = auth.uid() AND r.name = 'Education Official'
        )
    );

-- Admins have full access
CREATE POLICY "Admins have full access to recommendations" ON school_assessment_recommendations
    FOR ALL USING (
        EXISTS (
            SELECT 1 FROM hmr_users u
            JOIN hmr_user_roles r ON u.role = r.id
            WHERE u.id = auth.uid() AND r.name = 'Admin'
        )
    );

-- System can insert recommendations (for AI generation)
CREATE POLICY "System can insert recommendations" ON school_assessment_recommendations
    FOR INSERT WITH CHECK (true);

-- Comments for documentation
COMMENT ON TABLE school_assessment_recommendations IS 'AI-generated improvement recommendations based on assessment scores';
COMMENT ON COLUMN school_assessment_recommendations.category IS 'The scoring category this recommendation addresses';
COMMENT ON COLUMN school_assessment_recommendations.priority IS 'Priority level: high (<40%), medium (40-60%), low (>60% with improvement potential)';
COMMENT ON COLUMN school_assessment_recommendations.recommendation_text IS 'AI-generated actionable improvement suggestion';
COMMENT ON COLUMN school_assessment_recommendations.focus_areas IS 'Array of specific focus points within the category';
